# Generated by Django 5.1.4 on 2026-04-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prompt_text', models.TextField(verbose_name='Текст задания')),
                ('left_column_title', models.TextField(blank=True, null=True, verbose_name='Заголовок левой колонки')),
                ('right_column_title', models.TextField(blank=True, null=True, verbose_name='Заголовок правой колонки')),
            ],
            options={
                'verbose_name': 'Оценочное задание',
                'verbose_name_plural': 'Оценочные задания',
                'db_table': 'assessment_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentItemCompetence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Связь задания и компетенции',
                'verbose_name_plural': 'Связи заданий и компетенций',
                'db_table': 'assessment_item_competence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentItemRow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('left_text', models.TextField(blank=True, null=True, verbose_name='Левый текст')),
                ('right_text', models.TextField(blank=True, null=True, verbose_name='Правый текст')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='Порядок отображения')),
                ('correct_order', models.IntegerField(blank=True, null=True, verbose_name='Верный порядок')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Верный вариант')),
                ('open_answer_text', models.TextField(blank=True, null=True, verbose_name='Допустимый ответ')),
            ],
            options={
                'verbose_name': 'Строка задания',
                'verbose_name_plural': 'Строки задания',
                'db_table': 'assessment_item_row',
                'managed': False,
            },
        ),
    ]
