# Generated by Django 5.1.4 on 2026-04-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True, verbose_name='Наименование дисциплины')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'db_table': 'discipline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramDiscipline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Дисциплина учебного плана',
                'verbose_name_plural': 'Дисциплины учебных планов',
                'db_table': 'program_discipline',
                'managed': False,
            },
        ),
    ]
