# Generated by Django 5.1.4 on 2026-04-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_assessment_item_type_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Учёная степень',
                'verbose_name_plural': 'Учёные степени',
                'db_table': 'academic_degree',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicTitle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Учёное звание',
                'verbose_name_plural': 'Учёные звания',
                'db_table': 'academic_title',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentItemType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('name', models.TextField(unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип задания',
                'verbose_name_plural': 'Типы заданий',
                'db_table': 'assessment_item_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompetenceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип компетенции',
                'verbose_name_plural': 'Типы компетенций',
                'db_table': 'competence_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Уровень образования',
                'verbose_name_plural': 'Уровни образования',
                'db_table': 'education_level',
                'managed': False,
            },
        ),
    ]
