# Generated by Django 5.1.4 on 2026-04-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер кафедры')),
                ('short_name', models.TextField(verbose_name='Краткое название')),
                ('full_name', models.TextField(verbose_name='Полное название')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField(verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'db_table': 'teacher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherProgramDiscipline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Привязка преподавателя к дисциплине учебного плана',
                'verbose_name_plural': 'Привязки преподавателей к дисциплинам учебных планов',
                'db_table': 'teacher_program_discipline',
                'managed': False,
            },
        ),
    ]
