from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def apply_teacher_departments_schema(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS public.teacher_departments (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                teacher_id integer NOT NULL
                    REFERENCES public.teacher(id) DEFERRABLE INITIALLY DEFERRED,
                department_id integer NOT NULL
                    REFERENCES public.department(id) DEFERRABLE INITIALLY DEFERRED
            );

            CREATE UNIQUE INDEX IF NOT EXISTS teacher_departments_teacher_department_uidx
                ON public.teacher_departments (teacher_id, department_id);
            CREATE INDEX IF NOT EXISTS teacher_departments_teacher_idx
                ON public.teacher_departments (teacher_id);
            CREATE INDEX IF NOT EXISTS teacher_departments_department_idx
                ON public.teacher_departments (department_id);

            INSERT INTO public.teacher_departments (teacher_id, department_id)
            SELECT id, department_id
            FROM public.teacher
            WHERE department_id IS NOT NULL
            ON CONFLICT DO NOTHING;
            """
        )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер кафедры')),
                ('short_name', models.TextField(verbose_name='Краткое название')),
                ('full_name', models.TextField(verbose_name='Полное название')),
                ('head_teacher', models.ForeignKey(blank=True, db_column='head_teacher_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='headed_departments', to='teachers.teacher', verbose_name='Заведующий кафедрой')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField(verbose_name='ФИО')),
                ('academic_degree', models.ForeignKey(blank=True, db_column='academic_degree_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='core.academicdegree', verbose_name='Учёная степень')),
                ('academic_title', models.ForeignKey(blank=True, db_column='academic_title_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='core.academictitle', verbose_name='Учёное звание')),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='teachers.department', verbose_name='Основная кафедра')),
                ('departments', models.ManyToManyField(blank=True, db_table='teacher_departments', help_text='Дополнительные кафедры преподавателя; основная кафедра хранится в legacy-поле выше.', related_name='teachers_by_membership', to='teachers.department', verbose_name='Кафедры преподавателя')),
                ('user', models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь сайта')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'db_table': 'teacher',
                'managed': False,
            },
        ),
        migrations.RunPython(
            apply_teacher_departments_schema,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
