from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def apply_competence_indicator_schema(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS public.competence_indicator_import (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                educational_program_id integer NOT NULL
                    REFERENCES public.educational_program(id) ON DELETE CASCADE,
                uploaded_by_id integer
                    REFERENCES public.auth_user(id) ON DELETE SET NULL,
                source_filename character varying(255) NOT NULL,
                source_sha256 character varying(64) NOT NULL,
                status character varying(20) NOT NULL DEFAULT 'processing',
                total_rows integer NOT NULL DEFAULT 0,
                created_count integer NOT NULL DEFAULT 0,
                updated_count integer NOT NULL DEFAULT 0,
                skipped_count integer NOT NULL DEFAULT 0,
                error_count integer NOT NULL DEFAULT 0,
                warning_count integer NOT NULL DEFAULT 0,
                error_summary text,
                created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                completed_at timestamp with time zone,
                CONSTRAINT competence_indicator_import_counts_check CHECK (
                    total_rows >= 0
                    AND created_count >= 0
                    AND updated_count >= 0
                    AND skipped_count >= 0
                    AND error_count >= 0
                    AND warning_count >= 0
                ),
                CONSTRAINT competence_indicator_import_status_check CHECK (
                    status IN ('processing', 'completed', 'failed')
                )
            );

            CREATE INDEX IF NOT EXISTS comp_ind_imp_prog_date_idx
                ON public.competence_indicator_import (educational_program_id, created_at);
            CREATE INDEX IF NOT EXISTS comp_ind_imp_status_idx
                ON public.competence_indicator_import (status);
            CREATE INDEX IF NOT EXISTS comp_ind_imp_sha_idx
                ON public.competence_indicator_import (source_sha256);

            CREATE TABLE IF NOT EXISTS public.competence_indicator (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                competence_id integer NOT NULL
                    REFERENCES public.competence(id) ON DELETE CASCADE,
                last_import_id integer
                    REFERENCES public.competence_indicator_import(id) ON DELETE SET NULL,
                code character varying(50) NOT NULL,
                text text NOT NULL,
                source_file character varying(255) NOT NULL,
                source_table_number integer,
                source_row_number integer,
                created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT competence_indicator_competence_code_key UNIQUE (competence_id, code),
                CONSTRAINT competence_indicator_source_table_check CHECK (
                    source_table_number IS NULL OR source_table_number > 0
                ),
                CONSTRAINT competence_indicator_source_row_check CHECK (
                    source_row_number IS NULL OR source_row_number > 0
                )
            );

            CREATE INDEX IF NOT EXISTS comp_indicator_competence_idx
                ON public.competence_indicator (competence_id);
            CREATE INDEX IF NOT EXISTS comp_indicator_code_idx
                ON public.competence_indicator (code);
            """
        )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disciplines', '0002_program_discipline_active_in_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField(verbose_name='Код компетенции')),
                ('name', models.TextField(verbose_name='Наименование компетенции')),
                ('competence_type', models.ForeignKey(db_column='competence_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='competences', to='core.competencetype', verbose_name='Тип компетенции')),
                ('educational_program', models.ForeignKey(db_column='educational_program_id', on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='programs.educationalprogram', verbose_name='Образовательная программа')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенции',
                'db_table': 'competence',
                'managed': False,
                'constraints': [models.UniqueConstraint(fields=('educational_program', 'code'), name='competence_educational_program_id_code_key')],
            },
        ),
        migrations.CreateModel(
            name='CompetenceIndicatorImport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('source_sha256', models.CharField(max_length=64, verbose_name='SHA-256 файла')),
                ('status', models.CharField(choices=[('processing', 'Выполняется'), ('completed', 'Завершён'), ('failed', 'Ошибка')], default='processing', max_length=20, verbose_name='Статус')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Найдено индикаторов')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='Создано')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='Обновлено')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Пропущено')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('warning_count', models.PositiveIntegerField(default=0, verbose_name='Предупреждений')),
                ('error_summary', models.TextField(blank=True, null=True, verbose_name='Отчёт об ошибках')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('educational_program', models.ForeignKey(db_column='educational_program_id', on_delete=django.db.models.deletion.CASCADE, related_name='competence_indicator_imports', to='programs.educationalprogram', verbose_name='Образовательная программа')),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competence_indicator_imports', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Импорт индикаторов компетенций',
                'verbose_name_plural': 'Импорты индикаторов компетенций',
                'db_table': 'competence_indicator_import',
                'managed': False,
                'indexes': [
                    models.Index(fields=['educational_program', 'created_at'], name='comp_ind_imp_prog_date_idx'),
                    models.Index(fields=['status'], name='comp_ind_imp_status_idx'),
                    models.Index(fields=['source_sha256'], name='comp_ind_imp_sha_idx'),
                ],
                'constraints': [
                    models.CheckConstraint(condition=models.Q(status__in=('processing', 'completed', 'failed')), name='competence_indicator_import_status_check'),
                    models.CheckConstraint(condition=models.Q(total_rows__gte=0, created_count__gte=0, updated_count__gte=0, skipped_count__gte=0, error_count__gte=0, warning_count__gte=0), name='competence_indicator_import_counts_check'),
                ],
            },
        ),
        migrations.CreateModel(
            name='CompetenceIndicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, verbose_name='Код индикатора')),
                ('text', models.TextField(verbose_name='Текст индикатора')),
                ('source_file', models.CharField(max_length=255, verbose_name='Файл-источник')),
                ('source_table_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер таблицы в файле')),
                ('source_row_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер строки таблицы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('competence', models.ForeignKey(db_column='competence_id', on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='competencies.competence', verbose_name='Компетенция')),
                ('last_import', models.ForeignKey(blank=True, db_column='last_import_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_imported_indicators', to='competencies.competenceindicatorimport', verbose_name='Последний импорт')),
            ],
            options={
                'verbose_name': 'Индикатор достижения компетенции',
                'verbose_name_plural': 'Индикаторы достижения компетенций',
                'db_table': 'competence_indicator',
                'managed': False,
                'indexes': [
                    models.Index(fields=['competence'], name='comp_indicator_competence_idx'),
                    models.Index(fields=['code'], name='comp_indicator_code_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('competence', 'code'), name='competence_indicator_competence_code_key'),
                    models.CheckConstraint(condition=models.Q(source_table_number__isnull=True) | models.Q(source_table_number__gt=0), name='competence_indicator_source_table_check'),
                    models.CheckConstraint(condition=models.Q(source_row_number__isnull=True) | models.Q(source_row_number__gt=0), name='competence_indicator_source_row_check'),
                ],
            },
        ),
        migrations.CreateModel(
            name='DisciplineCompetence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('competence', models.ForeignKey(db_column='competence_id', on_delete=django.db.models.deletion.CASCADE, related_name='discipline_competences', to='competencies.competence', verbose_name='Компетенция')),
                ('program_discipline', models.ForeignKey(db_column='program_discipline_id', on_delete=django.db.models.deletion.CASCADE, related_name='discipline_competences', to='disciplines.programdiscipline', verbose_name='Дисциплина учебного плана')),
            ],
            options={
                'verbose_name': 'Связь дисциплины и компетенции',
                'verbose_name_plural': 'Связи дисциплин и компетенций',
                'db_table': 'discipline_competence',
                'managed': False,
                'constraints': [models.UniqueConstraint(fields=('program_discipline', 'competence'), name='discipline_competence_program_discipline_id_competence_id_key')],
            },
        ),
        migrations.RunPython(
            apply_competence_indicator_schema,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
