# Generated by Django 5.1.4 on 2026-04-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField(verbose_name='Код компетенции')),
                ('name', models.TextField(verbose_name='Наименование компетенции')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенции',
                'db_table': 'competence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisciplineCompetence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Связь дисциплины и компетенции',
                'verbose_name_plural': 'Связи дисциплин и компетенций',
                'db_table': 'discipline_competence',
                'managed': False,
            },
        ),
    ]
