-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.academic_degree
(
    id serial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT academic_degree_pkey PRIMARY KEY (id),
    CONSTRAINT academic_degree_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.academic_title
(
    id serial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT academic_title_pkey PRIMARY KEY (id),
    CONSTRAINT academic_title_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.assessment_item
(
    id serial NOT NULL,
    program_discipline_id integer NOT NULL,
    competence_id integer,
    assessment_item_type_id integer NOT NULL,
    prompt_text text COLLATE pg_catalog."default" NOT NULL,
    left_column_title text COLLATE pg_catalog."default",
    right_column_title text COLLATE pg_catalog."default",
    CONSTRAINT assessment_item_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.assessment_item_competence
(
    id serial NOT NULL,
    assessment_item_id integer NOT NULL,
    competence_id integer NOT NULL,
    CONSTRAINT assessment_item_competence_pkey PRIMARY KEY (id),
    CONSTRAINT assessment_item_competence_assessment_item_id_competence_id_key UNIQUE (assessment_item_id, competence_id)
);

CREATE TABLE IF NOT EXISTS public.assessment_item_row
(
    id serial NOT NULL,
    assessment_item_id integer NOT NULL,
    left_text text COLLATE pg_catalog."default",
    right_text text COLLATE pg_catalog."default",
    sort_order integer,
    correct_order integer,
    is_correct boolean,
    open_answer_text text COLLATE pg_catalog."default",
    CONSTRAINT assessment_item_row_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.assessment_item_type
(
    id serial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT assessment_item_type_pkey PRIMARY KEY (id),
    CONSTRAINT assessment_item_type_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.auth_user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    CONSTRAINT auth_user_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.auth_user_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.auth_user_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.competence
(
    id serial NOT NULL,
    educational_program_id integer NOT NULL,
    competence_type_id integer NOT NULL,
    code text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT competence_pkey PRIMARY KEY (id),
    CONSTRAINT competence_educational_program_id_code_key UNIQUE (educational_program_id, code)
);

CREATE TABLE IF NOT EXISTS public.competence_type
(
    id serial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT competence_type_pkey PRIMARY KEY (id),
    CONSTRAINT competence_type_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.department
(
    id serial NOT NULL,
    "number" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    short_name text COLLATE pg_catalog."default" NOT NULL,
    full_name text COLLATE pg_catalog."default" NOT NULL,
    head_teacher_id integer,
    CONSTRAINT department_pkey PRIMARY KEY (id),
    CONSTRAINT department_number_key UNIQUE ("number")
);

CREATE TABLE IF NOT EXISTS public.discipline
(
    id serial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT discipline_pkey PRIMARY KEY (id),
    CONSTRAINT discipline_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.discipline_competence
(
    id serial NOT NULL,
    program_discipline_id integer NOT NULL,
    competence_id integer NOT NULL,
    CONSTRAINT discipline_competence_pkey PRIMARY KEY (id),
    CONSTRAINT discipline_competence_program_discipline_id_competence_id_key UNIQUE (program_discipline_id, competence_id)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS public.education_level
(
    id serial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT education_level_pkey PRIMARY KEY (id),
    CONSTRAINT education_level_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.educational_program
(
    id serial NOT NULL,
    program_profile_id integer NOT NULL,
    department_id integer NOT NULL,
    admission_year smallint NOT NULL,
    CONSTRAINT educational_program_pkey PRIMARY KEY (id),
    CONSTRAINT educational_program_program_profile_id_department_id_admiss_key UNIQUE (program_profile_id, department_id, admission_year)
);

CREATE TABLE IF NOT EXISTS public.program_discipline
(
    id serial NOT NULL,
    educational_program_id integer NOT NULL,
    discipline_id integer NOT NULL,
    CONSTRAINT program_discipline_pkey PRIMARY KEY (id),
    CONSTRAINT program_discipline_educational_program_id_discipline_id_key UNIQUE (educational_program_id, discipline_id)
);

CREATE TABLE IF NOT EXISTS public.program_profile
(
    id serial NOT NULL,
    training_direction_id integer NOT NULL,
    code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT program_profile_pkey PRIMARY KEY (id),
    CONSTRAINT program_profile_code_key UNIQUE (code),
    CONSTRAINT program_profile_training_direction_id_name_key UNIQUE (training_direction_id, name)
);

CREATE TABLE IF NOT EXISTS public.teacher
(
    id serial NOT NULL,
    user_id integer,
    department_id integer NOT NULL,
    full_name text COLLATE pg_catalog."default" NOT NULL,
    academic_degree_id integer,
    academic_title_id integer,
    CONSTRAINT teacher_pkey PRIMARY KEY (id),
    CONSTRAINT teacher_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.teacher_program_discipline
(
    id serial NOT NULL,
    teacher_id integer NOT NULL,
    program_discipline_id integer NOT NULL,
    CONSTRAINT teacher_program_discipline_pkey PRIMARY KEY (id),
    CONSTRAINT teacher_program_discipline_teacher_id_program_discipline_id_key UNIQUE (teacher_id, program_discipline_id)
);

CREATE TABLE IF NOT EXISTS public.training_direction
(
    id serial NOT NULL,
    education_level_id integer NOT NULL,
    code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT training_direction_pkey PRIMARY KEY (id),
    CONSTRAINT training_direction_code_key UNIQUE (code)
);

ALTER TABLE IF EXISTS public.assessment_item
    ADD CONSTRAINT assessment_item_assessment_item_type_id_fkey FOREIGN KEY (assessment_item_type_id)
    REFERENCES public.assessment_item_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_assessment_item_assessment_item_type_id
    ON public.assessment_item(assessment_item_type_id);


ALTER TABLE IF EXISTS public.assessment_item
    ADD CONSTRAINT assessment_item_competence_id_fkey FOREIGN KEY (competence_id)
    REFERENCES public.competence (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_assessment_item_competence_id
    ON public.assessment_item(competence_id);


ALTER TABLE IF EXISTS public.assessment_item
    ADD CONSTRAINT assessment_item_program_discipline_id_fkey FOREIGN KEY (program_discipline_id)
    REFERENCES public.program_discipline (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_assessment_item_program_discipline_id
    ON public.assessment_item(program_discipline_id);


ALTER TABLE IF EXISTS public.assessment_item_row
    ADD CONSTRAINT assessment_item_row_assessment_item_id_fkey FOREIGN KEY (assessment_item_id)
    REFERENCES public.assessment_item (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_assessment_item_row_assessment_item_id
    ON public.assessment_item_row(assessment_item_id);


ALTER TABLE IF EXISTS public.assessment_item_competence
    ADD CONSTRAINT assessment_item_competence_assessment_item_id_fkey FOREIGN KEY (assessment_item_id)
    REFERENCES public.assessment_item (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_assessment_item_competence_assessment_item_id
    ON public.assessment_item_competence(assessment_item_id);


ALTER TABLE IF EXISTS public.assessment_item_competence
    ADD CONSTRAINT assessment_item_competence_competence_id_fkey FOREIGN KEY (competence_id)
    REFERENCES public.competence (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_assessment_item_competence_competence_id
    ON public.assessment_item_competence(competence_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_group_id_97559544
    ON public.auth_user_groups(group_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_user_id_6a12ed8b
    ON public.auth_user_groups(user_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_permission_id_1fbb5f2c
    ON public.auth_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_user_id_a95ead1b
    ON public.auth_user_user_permissions(user_id);


ALTER TABLE IF EXISTS public.competence
    ADD CONSTRAINT competence_competence_type_id_fkey FOREIGN KEY (competence_type_id)
    REFERENCES public.competence_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_competence_competence_type_id
    ON public.competence(competence_type_id);


ALTER TABLE IF EXISTS public.competence
    ADD CONSTRAINT competence_educational_program_id_fkey FOREIGN KEY (educational_program_id)
    REFERENCES public.educational_program (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_competence_educational_program_id
    ON public.competence(educational_program_id);


ALTER TABLE IF EXISTS public.department
    ADD CONSTRAINT department_head_teacher_id_fkey FOREIGN KEY (head_teacher_id)
    REFERENCES public.teacher (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_department_head_teacher_id
    ON public.department(head_teacher_id);


ALTER TABLE IF EXISTS public.discipline_competence
    ADD CONSTRAINT discipline_competence_competence_id_fkey FOREIGN KEY (competence_id)
    REFERENCES public.competence (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_discipline_competence_competence_id
    ON public.discipline_competence(competence_id);


ALTER TABLE IF EXISTS public.discipline_competence
    ADD CONSTRAINT discipline_competence_program_discipline_id_fkey FOREIGN KEY (program_discipline_id)
    REFERENCES public.program_discipline (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_discipline_competence_program_discipline_id
    ON public.discipline_competence(program_discipline_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.educational_program
    ADD CONSTRAINT educational_program_department_id_fkey FOREIGN KEY (department_id)
    REFERENCES public.department (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_educational_program_department_id
    ON public.educational_program(department_id);


ALTER TABLE IF EXISTS public.educational_program
    ADD CONSTRAINT educational_program_program_profile_id_fkey FOREIGN KEY (program_profile_id)
    REFERENCES public.program_profile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_educational_program_program_profile_id
    ON public.educational_program(program_profile_id);


ALTER TABLE IF EXISTS public.program_discipline
    ADD CONSTRAINT program_discipline_discipline_id_fkey FOREIGN KEY (discipline_id)
    REFERENCES public.discipline (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_program_discipline_discipline_id
    ON public.program_discipline(discipline_id);


ALTER TABLE IF EXISTS public.program_discipline
    ADD CONSTRAINT program_discipline_educational_program_id_fkey FOREIGN KEY (educational_program_id)
    REFERENCES public.educational_program (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_program_discipline_educational_program_id
    ON public.program_discipline(educational_program_id);


ALTER TABLE IF EXISTS public.program_profile
    ADD CONSTRAINT program_profile_training_direction_id_fkey FOREIGN KEY (training_direction_id)
    REFERENCES public.training_direction (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_program_profile_training_direction_id
    ON public.program_profile(training_direction_id);


ALTER TABLE IF EXISTS public.teacher
    ADD CONSTRAINT teacher_academic_degree_id_fkey FOREIGN KEY (academic_degree_id)
    REFERENCES public.academic_degree (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.teacher
    ADD CONSTRAINT teacher_academic_title_id_fkey FOREIGN KEY (academic_title_id)
    REFERENCES public.academic_title (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.teacher
    ADD CONSTRAINT teacher_department_id_fkey FOREIGN KEY (department_id)
    REFERENCES public.department (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_teacher_department_id
    ON public.teacher(department_id);


ALTER TABLE IF EXISTS public.teacher
    ADD CONSTRAINT teacher_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_teacher_user_id
    ON public.teacher(user_id);


ALTER TABLE IF EXISTS public.teacher_program_discipline
    ADD CONSTRAINT teacher_program_discipline_teacher_id_fkey FOREIGN KEY (teacher_id)
    REFERENCES public.teacher (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_teacher_program_discipline_teacher_id
    ON public.teacher_program_discipline(teacher_id);


ALTER TABLE IF EXISTS public.teacher_program_discipline
    ADD CONSTRAINT teacher_program_discipline_program_discipline_id_fkey FOREIGN KEY (program_discipline_id)
    REFERENCES public.program_discipline (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_teacher_program_discipline_program_discipline_id
    ON public.teacher_program_discipline(program_discipline_id);


ALTER TABLE IF EXISTS public.training_direction
    ADD CONSTRAINT training_direction_education_level_id_fkey FOREIGN KEY (education_level_id)
    REFERENCES public.education_level (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_training_direction_education_level_id
    ON public.training_direction(education_level_id);

END;
