# Generated by Django 5.1.4 on 2026-04-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admission_year', models.SmallIntegerField(verbose_name='Год набора')),
            ],
            options={
                'verbose_name': 'Образовательная программа',
                'verbose_name_plural': 'Образовательные программы',
                'db_table': 'educational_program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Код профиля')),
                ('name', models.TextField(verbose_name='Наименование профиля')),
            ],
            options={
                'verbose_name': 'Профиль программы',
                'verbose_name_plural': 'Профили программ',
                'db_table': 'program_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingDirection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код направления')),
                ('name', models.TextField(verbose_name='Наименование направления')),
            ],
            options={
                'verbose_name': 'Направление подготовки',
                'verbose_name_plural': 'Направления подготовки',
                'db_table': 'training_direction',
                'managed': False,
            },
        ),
    ]
