from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def apply_plx_import_draft_schema(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS public.program_plx_import_draft (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                uploaded_by_id integer NOT NULL
                    REFERENCES public.auth_user(id) ON DELETE CASCADE,
                existing_program_id integer
                    REFERENCES public.educational_program(id) ON DELETE SET NULL,
                source_filename character varying(255) NOT NULL,
                dto_payload jsonb NOT NULL,
                created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                expires_at timestamp with time zone NOT NULL
            );

            CREATE INDEX IF NOT EXISTS plx_draft_user_created_idx
                ON public.program_plx_import_draft (uploaded_by_id, created_at);
            CREATE INDEX IF NOT EXISTS plx_draft_expires_idx
                ON public.program_plx_import_draft (expires_at);
            """
        )


class Migration(migrations.Migration):
    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramPlxImportDraft',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_filename', models.CharField(max_length=255, verbose_name='Имя PLX-файла')),
                ('dto_payload', models.JSONField(verbose_name='Структурированные данные PLX')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(verbose_name='Действителен до')),
                ('existing_program', models.ForeignKey(blank=True, db_column='existing_program_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plx_import_drafts', to='programs.educationalprogram', verbose_name='Существующая программа')),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by_id', on_delete=django.db.models.deletion.CASCADE, related_name='program_plx_import_drafts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Черновик импорта PLX',
                'verbose_name_plural': 'Черновики импорта PLX',
                'db_table': 'program_plx_import_draft',
                'managed': False,
                'indexes': [
                    models.Index(fields=['uploaded_by', 'created_at'], name='plx_draft_user_created_idx'),
                    models.Index(fields=['expires_at'], name='plx_draft_expires_idx'),
                ],
            },
        ),
        migrations.RunPython(
            apply_plx_import_draft_schema,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
